services:
  - type: web
    name: group manager
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: API_HASH
        sync: false
      - key: API_ID
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: EVENT_LOGS
        sync: false
      - key: SUPPORT_CHAT
        sync: false
      - key: JOIN_LOGGER
        sync: false
      - key: START_IMG
        sync: false
      - key: BAN_STICKER
        sync: false





